services:
  claude-api:
    build: .
    container_name: claude-max-api
    ports:
      - "47291:8080"
    volumes:
      # Mount Docker-specific agents directory as .claude/agents in container
      - ./docker-agents:/app/.claude/agents:ro
      # Mount output styles directory for custom Claude output formats
      - ./docker-output-styles:/home/claudeuser/.claude/output-styles:ro
      # Persist Claude CLI authentication across container restarts
      - claude_auth:/home/claudeuser/.claude
    environment:
      - PYTHONUNBUFFERED=1
    working_dir: /app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 300s
      timeout: 60s
      retries: 3
      start_period: 60s
    networks:
      - claude-network

volumes:
  claude_auth:
    driver: local

networks:
  claude-network:
    driver: bridge